name: Feature request
description: Propose a new feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: "What user problem are we solving?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "Describe the solution you’d like"

  - type: textarea
    id: scope
    attributes:
      label: Scope & out-of-scope

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
